[package]
name = "zorro"
version = "0.0.1"
authors = ["chrisftw", "roxannedunn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.16.8"
base64 = "0.13.0"
lazy_static = "1.4.0"
